swagger: '2.0'
info:
  version: "1.0.0"
  title: API de Votes et Images
  description: API pour gérer les votes et les images dans le jeu MemeBattle
paths:
  /vote:
    post:
      summary: Voter pour une image
      description: Permet à un joueur de voter pour une image dans le jeu
      parameters:
        - name: idImage
          in: query
          description: ID de l'image à voter
          required: true
          type: string
        - name: idJoueur
          in: query
          description: ID du joueur qui effectue le vote
          required: true
          type: string
      responses:
        '200':
          description: Vote réussi
          schema:
            $ref: '#/definitions/ReponseVote'
        '400':
          description: Requête invalide
        '404':
          description: Image ou joueur introuvable

  /classement:
    get:
      summary: Obtenir le classement des joueurs
      responses:
        200:
          description: Classement récupéré avec succès
          schema:
            type: array
            items:
              type: object
              properties:
                pseudo:
                  type: string
                  description: Pseudo du joueur
                  example: wabfall
                score:
                  type: integer
                  description: Score du joueur
                  example: 800
        400:
          description: Requête invalide

definitions:
  ReponseVote:
    type: object
    properties:
      idImage:
        type: string
        description: ID de l'image votée
      idJoueur:
        type: string
        description: ID du joueur ayant effectué le vote
